# Generated by Django 2.0.6 on 2018-07-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0002_auto_20180709_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest_instance',
            name='rsvp_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
