# Generated by Django 2.0.6 on 2018-07-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0003_guest_instance_rsvp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_instance',
            name='rsvp_status',
            field=models.BooleanField(default=False),
        ),
    ]
