# Generated by Django 2.0.6 on 2018-07-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0004_auto_20180710_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_status',
            field=models.BooleanField(default=False),
        ),
    ]
