# Generated by Django 2.0.6 on 2018-07-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
    ]
