# Generated by Django 2.0.7 on 2018-07-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0002_auto_20180716_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_key',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
