# Generated by Django 2.0.7 on 2018-08-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0006_auto_20180725_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='dish_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
