# Generated by Django 2.0.7 on 2018-08-08 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0007_assignment_dish_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Dish_Tally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_needed', models.IntegerField(default=0)),
                ('app_assigned', models.IntegerField(default=0)),
                ('soup_needed', models.IntegerField(default=0)),
                ('soup_assigned', models.IntegerField(default=0)),
                ('salad_needed', models.IntegerField(default=0)),
                ('salad_assigned', models.IntegerField(default=0)),
                ('entree_needed', models.IntegerField(default=0)),
                ('entree_assigned', models.IntegerField(default=0)),
                ('dessert_needed', models.IntegerField(default=0)),
                ('dessert_assigned', models.IntegerField(default=0)),
                ('beverage_needed', models.IntegerField(default=0)),
                ('beverafe_assigned', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potlucks.Event')),
            ],
        ),
    ]
