# Generated by Django 2.0.7 on 2018-08-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0008_event_dish_tally'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_dish_tally',
            old_name='beverafe_assigned',
            new_name='beverage_assigned',
        ),
    ]
